# Generated by Django 3.2.10 on 2022-02-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_department_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
    ]
